### ISSUE TITLE
Add transferring to the bank

### ISSUE THREAD

**Issue by Rockefay** [Purgaty/EurobusinessHelper#43]

**Comment by Endrelish** [comment]
@Rockefay Backend done.
I added new event type to `src/EurobusinessHelper.UI.ASP/app/src/Services/Hubs/Types/types.ts` and handled its logging.
To do on FE: add another button with transfer in the place from the ss below:
![image](https://github.com/Purgaty/EurobusinessHelper/assets/22938921/ff171b9d-2e67-41bb-a8b7-11e6937cbc1c)

BE call is done accordingly to player transfer, but with the property `accountId` left empty

**Comment by Endrelish** [comment]
@Rockefay Continue working on the created branch, when the feature is done we'll merge both FE and BE in this PR
